### PR TITLE
Follow refactorings in Jet

### PR DESCRIPTION
**Pull request by viliam-durina**
Can be merged after hazelcast/hazelcast-jet#452 is merged.

### CODE REVIEW

**Comment by cangencer** [comment]
verify

**Comment by cangencer** [comment]
verify

**Comment by viliam-durina** [comment]
verify

**Comment by viliam-durina** [comment]
The compilation still fails, we have to wait until new SNAPSHOT version is built

**Comment by viliam-durina** [comment]
verify

**Pull request merged**
